# https://github.com/github/issue-labeler#basic-examples

dgraph:
  - "@auth/dgraph-adapter"

dynamodb:
  - "@auth/dynamodb-adapter"

fauna:
  - "@next-auth/fauna-adapter"

firebase:
  - "@next-auth/firebase-adapter"

mikro-orm:
  - "@next-auth/mikro-orm-adapter"

mongodb:
  - "@auth/mongodb-adapter"

neo4j:
  - "@next-auth/neo4j-adapter"

pouchdb:
  - "@next-auth/pouchdb-adapter"

prisma:
  - "@auth/prisma-adapter"

sequelize:
  - "@next-auth/sequelize-adapter"

supabase:
  - "@next-auth/supabase-adapter"

typeorm:
  - "@auth/typeorm-adapter"

upstash-redis:
  - "@auth/upstash-redis-adapter"

xata:
  - "@next-auth/xata-adapter"
