test:
  - test/**/*

documentation:
  - www/**/*
  - ./**/*.md

providers:
  - src/providers/**/*
  - www/docs/configuration/providers.md
  - test/integration/**/*

adapters:
  - src/adapters/**/*
  - www/docs/schemas/adapters.md

databases:
  - www/docs/schemas/*.md
  - test/docker/databases/**/*
  - www/docs/configuration/databases.md
  - test/fixtures/**/*