# Should be synced from v4 branch
# nextauthjs/next-auth-example:
#  - source: apps/example-nextjs
#    dest: .
#    deleteOrphaned: true
#  - .github/FUNDING.yml
#  - LICENSE

nextauthjs/sveltekit-auth-example:
  - source: apps/example-sveltekit
    dest: .
    deleteOrphaned: true
  - .github/FUNDING.yml
  - LICENSE

nextauthjs/next-auth-gatsby-example:
  - source: apps/playground-gatsby
    dest: .
    deleteOrphaned: true
  - .github/FUNDING.yml
  - LICENSE


nextauthjs/solid-start-auth-example:
  - source: apps/example-solid-start
    dest: .
    deleteOrphaned: true
  - .github/FUNDING.yml
  - LICENSE
