export * from "./external";
export { createClient } from "edgedb";
import * as $ from "./reflection";
import * as $syntax from "./syntax";
import * as $op from "./operators";
import _std from "./modules/std";
import _cal from "./modules/cal";
import _cfg from "./modules/cfg";
import _schema from "./modules/schema";
import _sys from "./modules/sys";
import _default from "./modules/default";
import _math from "./modules/math";
declare const ExportDefault: typeof _std & typeof _default & $.util.OmitDollarPrefixed<typeof $syntax> & typeof $op & {
    "std": typeof _std;
    "cal": typeof _cal;
    "cfg": typeof _cfg;
    "schema": typeof _schema;
    "sys": typeof _sys;
    "default": typeof _default;
    "math": typeof _math;
};
declare const Cardinality: typeof $.Cardinality;
declare type Cardinality = $.Cardinality;
export declare type Set<Type extends $.BaseType, Card extends $.Cardinality = $.Cardinality.Many> = $.TypeSet<Type, Card>;
export default ExportDefault;
export { Cardinality };
