-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE accounts (
--     id uuid DEFAULT gen_random_uuid() NOT NULL,
--     type text NOT NULL,
--     provider text NOT NULL,
--     "providerAccountId" text NOT NULL,
--     refresh_token text,
--     access_token text,
--     expires_at bigint,
--     token_type text,
--     scope text,
--     id_token text,
--     session_state text,
--     oauth_token_secret text,
--     oauth_token text,
--     "userId" uuid NOT NULL,
--     refresh_token_expires_in bigint
-- );
--
-- CREATE TABLE sessions (
--     id uuid DEFAULT gen_random_uuid() NOT NULL,
--     "sessionToken" text NOT NULL,
--     "userId" uuid NOT NULL,
--     expires timestamptz
-- );
--
-- CREATE TABLE users (
--     id uuid DEFAULT gen_random_uuid() NOT NULL,
--     name text,
--     email text,
--     "emailVerified" timestamptz,
--     image text
-- );
--
-- CREATE TABLE verification_tokens (
--     token text NOT NULL,
--     identifier text NOT NULL,
--     expires timestamptz
-- );
--
-- ALTER TABLE ONLY accounts
--     ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);
--
-- ALTER TABLE ONLY sessions
--     ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);
--
-- ALTER TABLE ONLY users
--     ADD CONSTRAINT users_email_key UNIQUE (email);
--
-- ALTER TABLE ONLY users
--     ADD CONSTRAINT users_pkey PRIMARY KEY (id);
--
-- ALTER TABLE ONLY verification_tokens
--     ADD CONSTRAINT verification_tokens_pkey PRIMARY KEY (token);
--
-- ALTER TABLE ONLY accounts
--     ADD CONSTRAINT "accounts_userId_fkey" FOREIGN KEY ("userId") REFERENCES public.users(id) ON UPDATE RESTRICT ON DELETE CASCADE;
--
-- ALTER TABLE ONLY sessions
--     ADD CONSTRAINT "sessions_userId_fkey" FOREIGN KEY ("userId") REFERENCES public.users(id) ON UPDATE RESTRICT ON DELETE CASCADE;
