-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.verification_tokens
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    identifier text COLLATE pg_catalog."default",
    token text COLLATE pg_catalog."default",
    expires timestamp with time zone,
    CONSTRAINT verification_tokens_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.verification_tokens
    OWNER to postgres;

GRANT ALL ON TABLE public.verification_tokens TO anon;

GRANT ALL ON TABLE public.verification_tokens TO authenticated;

GRANT ALL ON TABLE public.verification_tokens TO postgres;

GRANT ALL ON TABLE public.verification_tokens TO service_role;
